name: grocery_delivery_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  lucide_icons_flutter: ^3.1.14+2
  google_fonts: ^8.1.0
  provider: ^6.1.5+1
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Configuration for Flutter Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # Icons framework handles adaptive backgrounds better from SDK 21+
  # Optional: For Android 8.0+ adaptive icons, uncomment these lines if you have separate foreground/backgrounds
  # adaptive_icon_background: "#FFFFFF" # Or use AppColors.background hex code
  # adaptive_icon_foreground: "assets/images/app_logo_foreground.png"

# Configuration for Flutter Native Splash
flutter_native_splash:
  color: "#ffffff" # Replace with your exact AppColors.background hex string
  image: "assets/images/splash_logo.png" # Ensure this image is optimized for various screen sizes
  
  # Ensures the splash image scales elegantly across modern device aspect ratios
  android_gravity: center
  ios_content_mode: center

  # Optional: Controls visibility of the system status/navigation bar during splash screen execution
  fullscreen: true
  android: true
  ios: true
  android_12:
    image: "assets/images/splash_logo.png" # Ensure this image is optimized for various screen sizes
    color: "#ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/images/



